sudo: required
services: 
  - docker
before_install:
  - docker build -t analallena/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true analallena/react-test npm test

after_success:
  - docker build -t analallena/multi-client ./client
  - docker build -t analallena/multi-worker ./worker
  - docker build -t analallena/multi-nginx ./nginx
  - docker build -t analallena/multi-server ./server

# Log in to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to docker hub
  - docker push analallena/multi-client
  - docker push analallena/multi-nginx
  - docker push analallena/multi-server
  - docker push analallena/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env-2
  bucket_name: elasticbeanstalk-us-east-2-948902775090
  bucket_path: docker-multi
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
